development:
  adapter: postgresql
  encoding: unicode
  database: bookstore_development
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: bookstore_test
  pool: 5
  username: postgres
  password: root