development:
  adapter: postgresql
  encoding: unicode
  database: bookstore_development
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: bookstore_test
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: bookstore_production
  pool: 5
  host: localhost
  username: postgres
  password: root