Book.create(title: "The Ruby Programming Language", short_description: "The Ruby Programming Language", full_description: "The Ruby Programming Language", image: "", price: "10", category_id: "3")
Book.create(title: "Node Security", short_description: "Node Security", full_description: "Node Security", image: "", price: "15", category_id: "2")
Book.create(title: "Understanding Advanced JavaScrip", short_description: "Understanding Advanced JavaScrip", full_description: "Understanding Advanced JavaScrip", image: "", price: "14", category_id: "2")
Book.create(title: "Ember.js Application How-To Development", short_description: "Ember.js Application How-To Development", full_description: "Ember.js Application How-To Development", image: "", price: "10", category_id: "2")
Book.create(title: "RubyMotion iOS Development Essentials", short_description: "RubyMotion iOS Development Essentials", full_description: "RubyMotion iOS Development Essentials", image: "", price: "15", category_id: "1")
Book.create(title: "AngularJS Starter", short_description: "AngularJS Starter", full_description: "AngularJS Starter", image: "", price: "10", category_id: "2")
Category.create(name: "ios")
Category.create(name: "js")
Category.create(name: "ruby")
Author.create(first_name: "Sam", last_name: "Ruby", description: "")
Author.create(first_name: "Same", last_name: "Rubyy", description: "")
Author.create(first_name: "Sama", last_name: "Rubyu", description: "")
Author.create(first_name: "Samm", last_name: "Rubi", description: "")
Author.create(first_name: "Dave", last_name: "Thomas", description: "")
Author.create(first_name: "David", last_name: "Heinem", description: "")
