Book.create(title: "The Ruby Programming Language", short_description: "The Ruby Programming Language", full_description: "The Ruby Programming Language", image: "", price: "10", category_id: "3")
Book.create(title: "RubyMotion iOS Development Essentials", short_description: "RubyMotion iOS Development Essentials", full_description: "RubyMotion iOS Development Essentials", image: "", price: "15", category_id: "1")
Book.create(title: "Understanding Advanced JavaScrip", short_description: "Understanding Advanced JavaScrip", full_description: "Understanding Advanced JavaScrip", image: "", price: "14", category_id: "2")
Category.create(name: "ios")
Category.create(name: "js")
Category.create(name: "ruby")
Author.create(first_name: "Sam", last_name: "Ruby", description: "")
Author.create(first_name: "Dave", last_name: "Thomas", description: "")
Author.create(first_name: "David", last_name: "Heinem", description: "")
